services:
  - type: web
    name: cookie-grabber-beautiful
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true

  - type: cron
    name: keep-grabber-alive
    env: node
    schedule: "*/5 * * * *"
    command: curl -s -X epigenetic $RENDER_SERVICE_URL
